### ISSUE TITLE
Linux-Server用了这个补丁之后好像服务端FPS变低很多

### ISSUE THREAD

**Issue by hapeman0314** [VeroFess/PalWorld-Server-Unoffical-Fix#11]

**Comment by VeroFess** [comment]
麻烦试一下最新的beta release

**Comment by hapeman0314** [comment]
> 麻烦试一下最新的beta release

我朋友说还是一样

**Comment by FierceTerrity** [comment]
> 麻烦试一下最新的beta release
Hi! Can you explain how to install the patch for linux server? I can not find the necessary files in the folder with pal server.

**Comment by alvin268** [comment]
> > 麻烦试一下最新的beta release
> 
> Hi! Can you explain how to install the patch for linux server? I can not find the necessary files in the folder with pal server.

Go to /home/steam/Steam/steamapps/common/PalServer/Pal/Binaries/Linux then replace the Palserver-Linux-Test file

**Comment by hapeman0314** [comment]
> > 麻烦试一下最新的beta release
> > Hi! Can you explain how to install the patch for linux server? I can not find the necessary files in the folder with pal server.

if u ues docker to deploy u need use this command like 
docker cp ./PalServer-Linux-Test-1.3-beta container_name:/home/steam/Steam/steamapps/common/PalServer/Pal/Binaries/Linux/PalServer-Linux-Test

if u dont know the detail contents ,u can into the docker  : docker exec -it container_name /bin/bash and then find out the file 

then , u need to change the file mode :  docker exec -u 0 -it container_name chmod +x /home/steam/Steam/steamapps/common/PalServer/Pal/Binaries/Linux/PalServer-Linux-Test

last, dont forget to restart your docker

**Comment by VeroFess** [comment]
> > 麻烦试一下最新的beta release
> 
> 我朋友说还是一样

我目前没有Linux的调试环境，可能需要周末了，我这里收到的反馈是升级到Update 3后，FPS 有部分提升，但到不了上个版本的水平，所以可能和官方更新的内容有一些关系

**Comment by hapeman0314** [comment]
> > > 麻烦试一下最新的beta release
> > 
> > 
> > 我朋友说还是一样
> 
> 我目前没有Linux的调试环境，可能需要周末了，我这里收到的反馈是升级到Update 3后，FPS 有部分提升，但到不了上个版本的水平，所以可能和官方更新的内容有一些关系

确实是跟上个版本比这个版本本身FPS就降低了很多。 大佬辛苦了 👍

**Comment by VeroFess** [comment]
如果方便的话请在linux下以以下方式启动服务端：

```perf record -e cycles:u -j any,u -o perf.data -- /path/to/pal/binary pal_args```

在运行四五个小时后将 perf.data 发送给我以便进行后续优化

**Comment by JinShichang** [comment]
我的正常，基本都维持在60FPS，不过该崩还是会崩，档也是照炸不误，我们存档已经是大后期了，提心吊胆的玩

**Comment by NepPure** [comment]
> perf record -e cycles:u -j any,u -o perf.data -- /path/to/pal/binary pal_args

PalServer.sh 文件内容为

```sh
#!/bin/sh
UE_TRUE_SCRIPT_NAME=$(echo \"$0\" | xargs readlink -f)
UE_PROJECT_ROOT=$(dirname "$UE_TRUE_SCRIPT_NAME")
chmod +x "$UE_PROJECT_ROOT/Pal/Binaries/Linux/PalServer-Linux-Test"
"$UE_PROJECT_ROOT/Pal/Binaries/Linux/PalServer-Linux-Test" Pal "$@" 
```

是修改成这样启动吗，不是很熟悉这个

```sh
#!/bin/sh
UE_TRUE_SCRIPT_NAME=$(echo \"$0\" | xargs readlink -f)
UE_PROJECT_ROOT=$(dirname "$UE_TRUE_SCRIPT_NAME")
chmod +x "$UE_PROJECT_ROOT/Pal/Binaries/Linux/PalServer-Linux-Test"
perf record -e cycles:u -j any,u -o perf.data -- "$UE_PROJECT_ROOT/Pal/Binaries/Linux/PalServer-Linux-Test" Pal "$@" 
```

**Comment by hapeman0314** [comment]
> 我的正常，基本都维持在60FPS，不过该崩还是会崩，档也是照炸不误，我们存档已经是大后期了，提心吊胆的玩

写个备份的shell脚本，再写一个任务定时备份就好了

**Comment by JinShichang** [comment]
> > 我的正常，基本都维持在60FPS，不过该崩还是会崩，档也是照炸不误，我们存档已经是大后期了，提心吊胆的玩
> 
> 写个备份的shell脚本，再写一个任务定时备份就好了

有啊 15分钟备份一次，不然怎么可能玩得到后期，中途已经回档无数次了，得有专人盯着这破服务端

**Comment by twh233** [comment]
> > > 我的正常，基本都维持在60FPS，不过该崩还是会崩，档也是照炸不误，我们存档已经是大后期了，提心吊胆的玩
> > 
> > 
> > 写个备份的shell脚本，再写一个任务定时备份就好了
> 
> 有啊 15分钟备份一次，不然怎么可能玩得到后期，中途已经回档无数次了，得有专人盯着这破服务端

这游戏本身存档不是非常频繁嘛，如果没定时备份应该也没关系吧，难道是官网的备份会导致存档损坏吗，不是很明白

**Comment by hapeman0314** [comment]
> > > > 我的正常，基本都维持在60FPS，不过该崩还是会崩，档也是照炸不误，我们存档已经是大后期了，提心吊胆的玩
> > > 
> > > 
> > > 写个备份的shell脚本，再写一个任务定时备份就好了
> > 
> > 
> > 有啊 15分钟备份一次，不然怎么可能玩得到后期，中途已经回档无数次了，得有专人盯着这破服务端
> 
> 这游戏本身存档不是非常频繁嘛，如果没定时备份应该也没关系吧，难道是官网的备份会导致存档损坏吗，不是很明白

服务端每次存档会覆盖之前的，没有备份。本地备份目前还不能应用到服务端

**Comment by twh233** [comment]
> > > > > 我的正常，基本都维持在60FPS，不过该崩还是会崩，档也是照炸不误，我们存档已经是大后期了，提心吊胆的玩
> > > > 
> > > > 
> > > > 写个备份的shell脚本，再写一个任务定时备份就好了
> > > 
> > > 
> > > 有啊 15分钟备份一次，不然怎么可能玩得到后期，中途已经回档无数次了，得有专人盯着这破服务端
> > 
> > 
> > 这游戏本身存档不是非常频繁嘛，如果没定时备份应该也没关系吧，难道是官网的备份会导致存档损坏吗，不是很明白
> 
> 服务端每次存档会覆盖之前的，没有备份。本地备份目前还不能应用到服务端

感谢回答，我也写个脚本定时存档吧

**Comment by VeroFess** [comment]
试试 https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/tag/1.3.0-Update-4-Beta

**Comment by Minidoracat** [comment]
> 试试 https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/tag/1.3.0-Update-4-Beta

替換後進不去

https://cdn.discordapp.com/attachments/456737824725794827/1200409074156716092/image.png

https://cdn.discordapp.com/attachments/456737824725794827/1200409320156844085/image.png
md5hash: a3f4d882fc0c0801c581e6c91a80342e

**Comment by hapeman0314** [comment]
> 试试 https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/tag/1.3.0-Update-4-Beta

现在稳定在fps稳定在50左右，比之前10+好多了

**Comment by Minidoracat** [comment]
> > 试试 https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/tag/1.3.0-Update-4-Beta
> 
> 现在稳定在fps稳定在50左右，比之前10+好多了

請問你有進去容器確認過檔案 hash 了嗎?
我不管怎換他都會版本錯誤，驗證回原版就能進去

**Comment by hapeman0314** [comment]
> > > 试试 https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/tag/1.3.0-Update-4-Beta
> > 
> > 
> > 现在稳定在fps稳定在50左右，比之前10+好多了
> 
> 請問你有進去容器確認過檔案 hash 了嗎? 我不管怎換他都會版本錯誤，驗證回原版就能進去

确认了

**Comment by Minidoracat** [comment]
> > > > 试试 https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/tag/1.3.0-Update-4-Beta
> > > 
> > > 
> > > 现在稳定在fps稳定在50左右，比之前10+好多了
> > 
> > 
> > 請問你有進去容器確認過檔案 hash 了嗎? 我不管怎換他都會版本錯誤，驗證回原版就能進去
> 
> 确认了

這就怪了，我試看看如何把遊戲版本驗證機制關了
