### ISSUE TITLE
开心版服务器端报错

### ISSUE THREAD

**Issue by panchenxin** [VeroFess/PalWorld-Server-Unoffical-Fix#12]
windows 0.1.3开心版服务器报错
![image](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/assets/35493597/00572199-ff3e-4c48-b813-6a21bb12bb66)

**Comment by panchenxin** [comment]
将文件是在PalServer\Engine\Binaries\Win64目录下运行的

**Comment by VeroFess** [comment]
嗯...没有用过，请提供完整目录信息

**Comment by panchenxin** [comment]
> 嗯...没有用过，请提供完整目录信息

我是直接将服务器文件夹放在桌面的，可能每个人服务器文件的位置不一样，所以如果程序能出一个选择服务器文件夹的功能就最好了！

**Comment by 330377782** [comment]
steamcmd服务器同样报错+1
