### ISSUE TITLE
Linux 服务器效果不明显

### ISSUE THREAD

**Issue by NepPure** [VeroFess/PalWorld-Server-Unoffical-Fix#13]
<img width="1495" alt="image" src="https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/assets/12379907/cca29207-ce41-45be-85f5-66c3bb7cfb7a">

波谷是设置的每天6点自动重启。

[1.3.0 Update 2](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/tag/1.3.0-Update-2)检查了文件hash确认是替换了的，目前来看CPU使用，和内存增长速度和更新前区别不大

更新了beta3跑一段时间看看

**Comment by Tianmasikong** [comment]
在我的机子上效果为内存消耗增长速度放缓，但还是在不断地增加并最终爆掉，具体体现为原先2h爆掉，现在3h爆掉。

**Comment by XBisATrouble** [comment]
Ubuntu 22.04 Beta3 提供一些数据参考
![image](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/assets/18672633/fbda4880-69ac-4acd-81df-c5c0f5bb8948)

**Comment by VeroFess** [comment]
如果可以请帮忙抓取完整的内存分配追踪以协助分析，目前我这里人比较少不是很好分析

**Comment by NepPure** [comment]
> 如果可以请帮忙抓取完整的内存分配追踪以协助分析，目前我这里人比较少不是很好分析

有抓内存的方法吗

**Comment by XBisATrouble** [comment]
> 如果可以请帮忙抓取完整的内存分配追踪以协助分析，目前我这里人比较少不是很好分析

好，感谢你的工作

**Comment by blacktail1937** [comment]
还是有效果的，内存涨的慢了很多。还是要上定时重启。

**Comment by VeroFess** [comment]
试试 https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/tag/1.3.0-Update-4-Beta

**Comment by NepPure** [comment]
> 试试 https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/tag/1.3.0-Update-4-Beta

@VeroFess 感谢大佬，更新后内存增长速度并无明显变化
![image](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/assets/12379907/ff5577d7-51ba-47a8-a321-35fe638415e2)
