### ISSUE TITLE
【BUG】使用Update-3-Beta，服务器内存还是会爆

### ISSUE THREAD

**Issue by tzf1003** [VeroFess/PalWorld-Server-Unoffical-Fix#17]
![image](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/assets/46259700/22396062-3bf3-4339-acab-7fecc06ac6eb)
服务器配置：Ubuntu 2核8g内存，

请问，我应该如何记录相关日志。

**Comment by VeroFess** [comment]
好像8G确实是不太够.jpg

**Comment by tzf1003** [comment]
>  我8G目前解决方案是  swap 分配32G。  写个crontab 凌晨定时重启。(不重启也能玩) 

感谢，我现在去试试

**Comment by eigeen** [comment]
8G不够，服务端在后期+有人在线情况下，跑到12G也正常。

**Comment by ShiinaRinne** [comment]
![image](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/assets/45081750/8f73ff35-7043-44f6-a22c-f72cea1b1052)

![image](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/assets/45081750/5ca37f5e-8829-4346-92e2-b4c6ca7bc5d1)
两个服务器，硬撑√
其中第二个是用了作者patch的版本
