### ISSUE TITLE
Error message "tdd.dll" missing when running on windows

### ISSUE THREAD

**Issue by danyi** [VeroFess/PalWorld-Server-Unoffical-Fix#20]
Error message "tdd.dll" missing when running on windows
But I installed all the required runtime environments
Please tell me what is this thing that needs dll

**Comment by howrain** [comment]
move it into PalServer\Pal\Binaries\Win64 and rename PalServer-Win64-Test-Cmd.exe , remember to back up

**Comment by danyi** [comment]
3q
