### ISSUE TITLE
丢失tbb.dll文件 该怎么解决 补全DX库也没用

### ISSUE THREAD

**Issue by MarkTianYi** [VeroFess/PalWorld-Server-Unoffical-Fix#23]
![image](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/assets/124068044/28ecc9c9-bee4-4a9d-ac55-b8d786229579)
感谢

**Comment by VeroFess** [comment]
https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/issues/4 与该问题重复

**Comment by MarkTianYi** [comment]
怎么给你打赏
