### ISSUE TITLE
打了补丁  掉线后回档。。。

### ISSUE THREAD

**Issue by kennponn** [VeroFess/PalWorld-Server-Unoffical-Fix#25]
俩服都是打完补丁 基本上同时掉的线 而且回档了

**Comment by VeroFess** [comment]
请问是linux还是Windows?原本的appid是什么？

**Comment by kennponn** [comment]
Linux 原本的appid 没注意呀

**Comment by VeroFess** [comment]
打开steam_appid.txt, 里面会保存原始的信息

**Comment by kennponn** [comment]
看到了 原本的为2394010

**Comment by kennponn** [comment]
现在数据回档该如何解决呢？

**Comment by VeroFess** [comment]
请问还有更详细的信息么？由于我并没有修改服务器的逻辑，理论上我的补丁不会引发这类问题

您可以确定不是由于已知的导致存档损坏的bug(如有人退出公会)导致的么？

**Comment by kennponn** [comment]
刚才进程中确实出现了两个服务端 我还好奇，难不成这段时间他们是在另一个服务端？现在正常了 只有一个服务端

**Comment by VeroFess** [comment]
如果没有正确覆盖或者正确停止确实可以与原本的服务端并存，因为其本身没有防止多开的机制

**Comment by kennponn** [comment]
他是三个进程 停了俩 可能导致了这个问题

**Comment by VeroFess** [comment]
我认为这和我的修补并没有直接的相关性，如果有方式复现请重新打开这个Issue

**Comment by kennponn** [comment]
好的
