### ISSUE TITLE
求解一下

### ISSUE THREAD

**Issue by hexiosr** [VeroFess/PalWorld-Server-Unoffical-Fix#35]
覆盖后运行提示：patten search failed sig: 40 53 56 57 48 ?? ?? ?? ?? ?? ?? 48 ?? ?? ?? ?? ????48 33 C4 48 89 ?????? ?? ?? ?? 49 8B D9 49 8B F8 48 8B F2 4D 85 C074 ?? 48 85 DB
请问下这是什啥原因 ，我下的这个版本的[1.3.0 Update 2](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/tag/1.3.0-Update-2)

**Comment by hexiosr** [comment]
Windows版本的

**Comment by hexiosr** [comment]
试了能正常进游戏，但是不知道为啥会提示这个东西

**Comment by VeroFess** [comment]
https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/issues/8 与该问题相同
