### ISSUE TITLE
tbb.dll not found

### ISSUE THREAD

**Issue by CNJACK47** [VeroFess/PalWorld-Server-Unoffical-Fix#4]
tbb.dll not found

**Comment by VeroFess** [comment]
Usually when you see this error, it means you placed the file incorrectly. Under Windows, you should place it in 

```<your steamcmd directory>\steamapps\common\PalServer\Pal\Binaries\Win64```

you should found ```PalServer-Win64-Test-Cmd.exe``` in this directory

**Comment by Supergenli** [comment]
What if I using the hosting server, how can I use your files on hosting server ? (I am the hosting renter)

**Comment by CNJACK47** [comment]
Thank you.

**Comment by CNJACK47** [comment]
> 通常，当您看到此错误时，这意味着您错误地放置了文件。在 Windows 下，您应该将其放置在
> 
> `<your steamcmd directory>\steamapps\common\PalServer\Pal\Binaries\Win64`
> 
> `PalServer-Win64-Test-Cmd.exe`你应该在这个目录中找到

Thank you.
