### ISSUE TITLE
租用伺服器的話, 要怎樣用你的修復檔呢?

### ISSUE THREAD

**Issue by Supergenli** [VeroFess/PalWorld-Server-Unoffical-Fix#7]
租用伺服器的话, 要怎样用你的修复档呢?
因为架服的工具都是HOSTING那边给承包了
没法直接使用你的EXE文件覆盖QQ

**Comment by tzf1003** [comment]
只能和服务商协商了，看服务商愿不愿意去使用这个修复档

**Comment by VeroFess** [comment]
有一些和我私下里关系比较好的服务商例如 https://www.wuyuidc.com/ 或者 https://www.rhymc.com/ 已经使用了这个补丁，其他服务商可能需要你自己联系

**Comment by MapleEve** [comment]
> 有一些和我私下里关系比较好的服务商例如 https://www.wuyuidc.com/ 或者 https://www.rhymc.com/ 已经使用了这个补丁，其他服务商可能需要你自己联系

旋律超售了，物语目前也有点。物语自己的ECS 还行，跑着不少游戏。
