### ISSUE TITLE
替换后运行出现error

### ISSUE THREAD

**Issue by Excalibur5100** [VeroFess/PalWorld-Server-Unoffical-Fix#8]
![image](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/assets/105792144/81253f8e-355e-4925-b52e-cb68181b7ab1)
![image](https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/assets/105792144/b250840b-0246-4037-b7dd-e6780b5aca15)
如图，启动时会接连出现2个error提示，但是能进入游戏，把提示框关掉之后，加入游戏/游戏过程中还会弹出第二个提示框，不知道什么情况或存在什么影响

**Comment by VeroFess** [comment]
你用了另一个群友写的补丁，我给他摇过来

**Comment by luciouskami** [comment]
只要二选一就行了，要么用我的补丁。要么替换。

**Comment by Excalibur5100** [comment]
> 只要二选一就行了，要么用我的补丁。要么替换。

噢，好的感谢。就是我这个服务器上的是自带的一个包里的，不知道大佬的补丁O(∩_∩)O
